### ISSUE TITLE
可以提供更多示例吗

### ISSUE THREAD

**Issue by eonezhang** [DFocusGroup/generator-umi#1]
如题, 现在脚手架生成的代码使用的 hook 很精典,期待能有更多的 sample 示例出来, 结合 umi 和简单业务场景总结出来的套路.

**Comment by leftstick** [comment]
脚手架毕竟不是示例应用。这个是中台系统的脚手架，通常一个中台系统包含的，一成不变的就只有登录了。内置其他业务不太合适。

如果你想看示例，那应该看[ant-design-pro](https://github.com/ant-design/ant-design-pro)更合适些

**Comment by leftstick** [comment]
@eonezhang 如果想多看看 `useModel` 的用法，可以看这个[js-interview-online](https://github.com/leftstick/js-interview-online)
