### ISSUE TITLE
请问这个脚手架是umi官方维护的吗

### ISSUE THREAD

**Issue by birdycn** [DFocusGroup/generator-umi#2]
请问这个脚手架是umi官方维护的吗

**Comment by leftstick** [comment]
目前不是的。但不排除可能移入 `umijs` 分组下。

项目之初是公司自己的脚手架，然后开源出来的。不过从 `umi@1` 开始一直到现在，持续维护升级。

**Comment by psw0714** [comment]
现在直接使用 yo umi生成脚手架为啥会提示 Path must be a string.

![image](https://user-images.githubusercontent.com/26177875/81374967-04510680-9133-11ea-82ad-982f52e2a0c0.png)
