### ISSUE TITLE
现在直接使用 yo umi生成脚手架,在start的时候为啥会提示 Path must be a string.

### ISSUE THREAD

**Issue by RyanPan-SW** [DFocusGroup/generator-umi#3]
![image](https://user-images.githubusercontent.com/26177875/81375077-45e1b180-9133-11ea-8a30-53c86d985aec.png)

**Comment by leftstick** [comment]
目前没遇到过，要不你试试别在有中文的路径下创建一个项目再试试？

**Comment by RyanPan-SW** [comment]
找到原因了，umi升级了， 3X的版本不兼容应该是，我退到umi 2X的就好了

**Comment by leftstick** [comment]
不兼容什么？中文目录？

**Comment by RyanPan-SW** [comment]
自动安装的umi版本是3X的，启动就会报错，不是中文目录的原因，看了umi的3X的版本，写法变动还挺大的
