### ISSUE TITLE
初始化生成项目报错@primary-color is undefined

### ISSUE THREAD

**Issue by wangyuan0108** [DFocusGroup/generator-umi#6]
初始化生成项目报错@primary-color is undefined，有几个less中的变量提示没找到

**Comment by wangyuan0108** [comment]
![image](https://user-images.githubusercontent.com/22407253/91162134-43b15c00-e6fe-11ea-8db5-f460a2668442.png)

**Comment by wangyuan0108** [comment]
@leftstick 看起来像是依赖包有点问题

**Comment by leftstick** [comment]
@wangyuan0108 ~~让我检查下。你是最新版的么？~~

找到问题了，上次新增动态主题切换功能改出的毛病。。。。简直了

**Comment by wangyuan0108** [comment]
@leftstick 嗯，好的，大佬威武，膜拜ing。。。。。。。

**Comment by leftstick** [comment]
@wangyuan0108  fixed in `4.4.2`

**Comment by wangyuan0108** [comment]
@leftstick ok
