### ISSUE TITLE
Error: getaddrinfo ENOTFOUND local.coupangdev.com

### ISSUE THREAD

**Issue by RyanPan-SW** [DFocusGroup/generator-umi#7]
新建的项目： 
yarn global add yo generator-umi之后 yo umi 创建项目，运行项目会有错，不能start 

![image](https://user-images.githubusercontent.com/26177875/93853637-cbcb5700-fce6-11ea-926c-167b81398550.png)

**Comment by leftstick** [comment]
@RyanPan-SW  fixed in `4.5.1`, try it again
